
#
# Path to your C++ compiler
#
CXX = /home/dmbutler/LPS/prerequisites/gcc/bin/g++

#
# Path the SheafSystem installation
#
SHEAF_LIB_DIR = /home/dmbutler/components-tutorial-5-2/build/Debug-contracts/lib
SHEAF_INC_DIR = /home/dmbutler/install/include
SHEAF_INSTALL_DIR = /home/dmbutler/install

example1: example1.cc
	$(CXX) -o example1 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example1.cc -lsheaves	

example2: example2.cc
	$(CXX) -o example2 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example2.cc -lsheaves	

example3: example3.cc
	$(CXX) -o example3 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example3.cc -lsheaves	

exampleA1: exampleA1.cc
	$(CXX) -o exampleA1 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) exampleA1.cc -lsheaves	

exampleA2: exampleA2.cc
	$(CXX) -o exampleA2 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) exampleA2.cc -lsheaves	