
#
# Copyright (c) 2013 Limit Point Systems, Inc. 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Path to your C++ compiler
#
CXX = 
#
# Path the SheafSystem installation
#
SHEAF_INSTALL_DIR = 
SHEAF_LIB_DIR = $(SHEAF_INSTALL_DIR)/Debug-contracts/lib
SHEAF_INC_DIR = $(SHEAF_INSTALL_DIR)/include

example1: example1.cc
	$(CXX) -o example1 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example1.cc -lsheaves	

example2: example2.cc
	$(CXX) -o example2 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example2.cc -lsheaves	

example3: example3.cc
	$(CXX) -o example3 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example3.cc -lsheaves	

example4: example4.cc
	$(CXX) -o example4 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example4.cc -lsheaves	

example5: example5.cc
	$(CXX) -o example5 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example5.cc -lsheaves	

example6: example6.cc
	$(CXX) -o example6 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example6.cc -lsheaves	

example7: example7.cc
	$(CXX) -o example7 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example7.cc -lsheaves	

example8: example8.cc
	$(CXX) -o example8 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example8.cc -lsheaves	

example9: example9.cc
	$(CXX) -o example9 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example9.cc -lsheaves	

example10: example10.cc
	$(CXX) -o example10 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example10.cc -lsheaves	

example11: example11.cc
	$(CXX) -o example11 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example11.cc -lsheaves	

example12: example12.cc
	$(CXX) -o example12 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example12.cc -lsheaves	

example13: example13.cc
	$(CXX) -o example13 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example13.cc -lsheaves	

example14: example14.cc
	$(CXX) -o example14 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example14.cc -lsheaves	

example15: example15.cc
	$(CXX) -o example15 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example15.cc -lsheaves	

exampleA1: exampleA1.cc
	$(CXX) -o exampleA1 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) exampleA1.cc -lsheaves	

exampleA2: exampleA2.cc
	$(CXX) -o exampleA2 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) exampleA2.cc -lsheaves	