
#
# Copyright (c) 2013 Limit Point Systems, Inc. 
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#
# Path to your C++ compiler
#
CXX = 

#
# Path the SheafSystem installation
#
SHEAF_INSTALL_DIR = 
SHEAF_LIB_DIR = $(SHEAF_INSTALL_DIR)/Debug-contracts/lib
SHEAF_INC_DIR = $(SHEAF_INSTALL_DIR)/include

example21: example21.cc
	$(CXX) -o example21 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example21.cc -lfiber_bundles -lsheaves	

example22: example22.cc
	$(CXX) -o example22 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example22.cc -lfiber_bundles -lsheaves	

example23: example23.cc
	$(CXX) -o example23 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example23.cc -lfiber_bundles -lsheaves	

example24: example24.cc
	$(CXX) -o example24 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example24.cc -lfiber_bundles -lsheaves	

example25: example25.cc
	$(CXX) -o example25 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example25.cc -lfiber_bundles -lsheaves	

example26: example26.cc
	$(CXX) -o example26 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example26.cc -lfiber_bundles -lsheaves	

example27: example27.cc
	$(CXX) -o example27 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example27.cc -lfiber_bundles -lsheaves	

example28: example28.cc
	$(CXX) -o example28 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example28.cc -lfiber_bundles -lsheaves	

example29: example29.cc
	$(CXX) -o example29 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example29.cc -lfiber_bundles -lsheaves	

example30: example30.cc
	$(CXX) -o example30 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example30.cc -lfiber_bundles -lsheaves	

example31: example31.cc
	$(CXX) -o example31 -I$(SHEAF_INC_DIR) -L$(SHEAF_LIB_DIR) example31.cc -lfiber_bundles -lsheaves	
